Portfolio: setup and mobile version skeleton pull request
Ahsan12356/portfolio-nolonger pull request #1
Opened 2022-06-30 15:28 UTC by Ahsan12356

This is a small project in which we had to make the toolbar and heading section of our portfolio website for mobile. We replicated this from Figma templates that were given.

2022-06-30 15:38 UTC, danmainah requested changes
Hi @Ahsan12356 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have any content in the readme file, kindly add content to your readme file using [this template.](https://github.com/microverseinc/readme-template/blob/master/README.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-30 16:22 UTC, Ahsan12356 commented
I have contents in my readme file!!!! Attached is my readme file. How can I get a filled readme file screenshot if there is no content?
![Screenshot from 2022-06-30 21-20-23](https://user-images.githubusercontent.com/22774319/176728364-96e0ed8a-9a73-4e02-857a-de025d82ceb7.png)

2022-06-30 16:28 UTC, Ahsan12356 commented
the readme file is already. How can I add extra content in readme file?
Attached is the screenshot of readme file.

On Thu, Jun 30, 2022 at 8:38 PM Daniel Maina ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Ahsan12356 <https://github.com/Ahsan12356> ,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
> You have submitted a project, that doesn't have any content in the readme
> file, kindly add content to your readme file using this template.
> <https://github.com/microverseinc/readme-template/blob/master/README.md>
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Ahsan12356/portfolio/pull/1#pullrequestreview-1025095901>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFNYEL6R6LEYA5R6O5GUSDTVRW5QJANCNFSM52JYWVGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-30 17:02 UTC, BertrandConxy commented
- [x] Hey @Ahsan12356. I would like to give you more information about what the previous reviewer wanted to mean.
It is true that you have README which has content but it is on the main branch, not the portfolio-mobile-skeleton. You should have added after creating this branch and as a result, you don't have it here on this branch. Please watch this [video ](https://www.loom.com/share/4a6537f5d1d54d2fb8776240869ddac5) and follow the advice given. As long as you have an updated README file on this branch, then it will be good to be reviewed.

2022-06-30 17:32 UTC, Ahsan12356 commented
Thankyou very much for letting me know. That's really nice of you my friend.
Can you suggest me a valid tutorial or video tutorial that shows the whole procedure of pulling requests and all that.
Thanks in advance!

2022-06-30 18:41 UTC, BertrandConxy requested changes
Hi @Ahsan12356 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- Good commit messages
- Linters are passing
- Project works well on my computer

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- You can find some tutorials as you asked me on Youtube. I would recommend [this one](https://www.youtube.com/watch?v=RGOj5yH7evk) and some documentation about git and git commands [here](https://www.w3schools.com/git/default.asp?remote=github)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 18:41 UTC, BertrandConxy commented on index.html
> +            </div>
- [x] [OPTIONAL] Great work here 👏. You were able to detect these details as they are on the Figma design templated you chose. It is really a great skill to pay attention to all details even the small ones. However, this status bar is just for the prototype. It should not be implemented while building the site. Imagine opening up your portfolio on your mobile phone and seeing that you have two status bars. The one from your phone and another one you designed in your browser 🤔. That would not seem good. I would suggest that you remove it.
- [x] Even if you may choose to remain with it, I can observe that these images you added are not appearing on the page. That means they do not exist. Look at the picture below 👇 
![image](https://user-images.githubusercontent.com/90222110/176747368-b1d73d3f-975c-4a45-8c46-99d1addd29b5.png)
This is caused by either of the following reasons:
- Images not present
- Image path is not correct
For your case, I can see that there is no folder called `images` as you referred it there. Please add the directory and the image files that you are referencing here because it looks like they are not present in your repo 🏃‍♂️

2022-06-30 18:41 UTC, BertrandConxy commented on index.html
> +            <a href="" class="my-logo">My Logo</a>
- [ ] Great Job here 👏. You have made your logo an anchor tag `<a>` which redirects to the home page. However You can replace the `My Logo` text with **your name**. Because it is like your logo, your brand name. Please make sure you correct that 😃.

2022-06-30 18:41 UTC, BertrandConxy commented on index.html
> +            <a href="#" class="bars"><img src="images/icon-menu.png" alt=""></a>
- [ ] You have really done a great job building this hamburger button but due to the reason why it is represented by the image or the icon in other words, and that image is not present due to the reason I have stated above in similar image case like this, the hamburger button is not appearing on your web page. You can observe it by yourself 👇 
![image](https://user-images.githubusercontent.com/90222110/176749959-be32c2be-1877-4cf4-b876-1a5eaae0f47b.png)
So, please as long as you have added the images folder in your repository and added also your image files in it, I am sure that they will be appearing 😺

2022-06-30 18:41 UTC, BertrandConxy commented on index.html
> +        </ul>
- [ ] The same thing for your social media icons. Please try to make them appear on your web page because right now no one can see them.

2022-06-30 18:41 UTC, BertrandConxy commented on style.css
> +  background-color: #f7f7f9;
- [ ] While the design for the body is good, I would suggest that you change the color of the body to white (i.e: #fff). This will help you to have the design look exactly the same as the Figma design given.

2022-06-30 18:41 UTC, BertrandConxy commented on style.css
> +.tool_bar {
- [x] This tool bar should be aligned well with the rest of the content. What I mean is to add some margin to the left so that it is on same position as there's of content.
**This is your design**
![image](https://user-images.githubusercontent.com/90222110/176752128-fe6ca2f3-c41d-4f40-8a63-778c7f247f49.png)
**This is Figma design**
![image](https://user-images.githubusercontent.com/90222110/176752400-26ef1657-6464-4541-82b5-71b75e53c45a.png)

Look how the logo is aligned well with the rest of the content. Please correct on that 😃 

- [x] Lastly, you can see that there are some graphics, like those curved blue drawings that are in the Figma design. These should also be implemented in your design. You can download them and then include them in your web page by positioning them in the right way 😺.

2022-06-30 19:17 UTC, Ahsan12356 commented on style.css
> +  background-color: #f7f7f9;
Actually background color of the body in Figma is #f7f7f9 because the bottom left border-radius should be visible. In the case of white color #fff, that radius would not be visible.

2022-06-30 19:22 UTC, Ahsan12356 commented
I made all the changes emphasized by you. Now hopefully, there is no other issue.

2022-07-01 06:57 UTC, OmarRamoun approved these changes
# 🟢 Project Approved! 🏆

## Hi @Ahsan12356 👋

Your project is complete! ✔️ 🏁. This is the First Project 1️⃣ You get Approved ✔️! in microverse 🌐.

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- :heavy_check_mark: very very good communication in PR :clap:
- ✔️ Descriptive commit messages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 07:38 UTC, merged